name: CI

on:
  pull_request:
    branches: ["master"]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Jest tests
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: tests + build with Node.js ${{ matrix.node-version }} then push to PR branch
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run test
